### ISSUE TITLE
AGIC discontinued?

### ISSUE THREAD

**Issue by freeo** [claranet/terraform-azurerm-aks#4]
I've noticed your AGIC submodule isn't available after v4.2 anymore. May I ask whats the reasoning behind the discontinuation? Security issues? I'm using AGIC v4.2 in production currently and need to assess if I need to migrate/fork.

**Comment by Shr3ps** [comment]
Hello,

Thanks for your issue. The AGIC sub-module is still maintained and used, but it has moved in v4.3.0 (and upper version) to this new path: https://github.com/claranet/terraform-azurerm-aks/tree/v4.5.0/tools/agic
Thanks to your issue, it seems the README file is not up to date. We will fix that.

**Comment by freeo** [comment]
Thank you! Glad to hear :smiley:  

Closed
