### ISSUE TITLE
support for existing appgtw

### ISSUE THREAD

**Issue by brunoscota** [claranet/terraform-azurerm-aks#5]
I would like to suggest you to add the feature to support an existing AppGtw. This module is great and it could be even better with this feature.

**Comment by Shr3ps** [comment]
Hello @brunoscota ,
can you please detail a bit more what do you want to do?
The actual module already have the option `var.agic_enabled` to enable or disable AGIC creation within the module.

**Comment by brunoscota** [comment]
thks for you response.. 

And how do I attach the existing agw. I thought it was something like this: `var.appgateway_id` or similar

**Comment by jmapro** [comment]
Hello @brunoscota ,

Thanks for the suggestion ! We will check how to implement brownfield deployment on the AGIC.

**Comment by jmapro** [comment]
Released in `v7.1.0`

**Comment by BzSpi** [comment]
You're welcome. 

Be aware that we have only supported linking an existing application gateway at the infrastructure level and that you need to manage it well with the according CRD as mentioned in the documentaion.

https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-existing.md#multi-cluster--shared-app-gateway
